# Generated by Django 4.2.3 on 2023-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_webhook", "0002_webhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
