# Generated by Django 4.2.3 on 2024-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_webhook", "0003_alter_webhook_created_alter_webhook_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="webhooksecret",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
