# Generated by Django 5.1 on 2026-04-17 17:36

import django.core.validators
import django_webhook.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0004_alter_webhookevent_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooktopic",
            name="name",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\w+\\.\\w+\\/(create|update|delete)",
                        message="Topic must match: \\w+\\.\\w+\\/(create|update|delete)",
                    ),
                    django_webhook.validators.validate_topic_model,
                ],
            ),
        ),
    ]
