# Generated by Django 5.0.6 on 2024-08-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0002_user_join_date_user_last_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelWithFileField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
